# Generated by Django 3.1.1 on 2021-01-08 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(blank=True, max_length=255)),
                ('countries_ids', models.CharField(blank=True, max_length=255)),
                ('tenders', models.BooleanField(default=True)),
                ('webs', models.BooleanField(default=False)),
                ('profiles', models.BooleanField(default=False)),
                ('users', models.BooleanField(default=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privilege', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
